### ISSUE TITLE
no backend avaliable 

### ISSUE THREAD

**Issue by ginghus-khan2000** [jphalip/ticlib#4]
Hi,  I appreciate the effort of creating the library.  I have a problem (of course, sorry).  I've installed
-Python 3.9.x
-Pip3
-ticlib
-usbpy

I try running your example code and get this error.
=================
Traceback (most recent call last):
  File "/Users/admin/Documents/Python Programming/tic test 2.py", line 1, in <module>
    from src.ticlib import TicUSB
ModuleNotFoundError: No module named 'src'
==============
so I took out the src. and got
==================
Traceback (most recent call last):
  File "/Users/admin/Documents/Python Programming/tic test 2.py", line 4, in <module>
    tic = TicUSB()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ticlib/ticlib.py", line 634, in __init__
    self.usb = usb_core.find(**params)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/usb/core.py", line 1309, in find
    raise NoBackendError('No backend available')
usb.core.NoBackendError: No backend available
==================
I'm pretty much a noob to Python programming but trying.  Can you suggest a solution?  What am I doing wrong?

Khan

**Comment by ginghus-khan2000** [comment]
I got it working.  Had to install HomeBrew and libusb.  Works a treat.  I just hate to think what I've done to my machine to install libusb (openUSB?).  Thanks for the library.  :)
Khan

**Comment by Em607867** [comment]
> I got it working. Had to install HomeBrew and libusb. Works a treat. I just hate to think what I've done to my machine to install libusb (openUSB?). Thanks for the library. :) Khan

Hi, 
Did you end up using SRC still or removing SRC? 

Also when you connect a device, are you able to disconnect? I can't seem to find the function to do that.

**Comment by ginghus-khan2000** [comment]
No, didn't have to install SRC. I use IDLE, the Python interpreter built into to OS X.  I haven't had any trouble with disconnecting a device.  Just yank it out.  Just check to see if connected using Pololu stepper controller software.

The one thing I did have to change (in the Pololu software) was to disable the "enable timeout".

Eric


________________________________
